### ISSUE TITLE
frontend

### ISSUE THREAD

**Issue by Muriel13** [Muriel13/chef-d-oeuvre#1]

**Comment by Muriel13** [comment]
Les éléments du frontend

**Comment by Muriel13** [comment]
```html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="cuisine.css">
    <title> Recette </title>
</head>

<body>

    <header>
        
        <section id="form">
        <img class="logo" src="logu.jpeg" alt="Logo Cuisine">

        <div class="form">
       <form>
  <input id="search" type="search" placeholder="Search..." autofocus required />
  <button id="GO" type="submit">Go</button>    
</form>
        </div>
        </section>

    <section class="content">
         <nav class="menu">
        <div id="wrap">
            <header class="header">
                <nav class="nav">
                    <a href="#wrap" id="open">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="34px" height="27px" viewBox="0 0 34 27" enable-background="new 0 0 34 27" xml:space="preserve">
                        <rect fill="#FFFFFF" width="34" height="4"/>
                        <rect y="11" fill="#FFFFFF" width="34" height="4"/>
                        <rect y="23" fill="#FFFFFF" width="34" height="4"/>
                        </svg>
                    </a>
                    <a href="#" id="close">×</a>
                    <h1><a href="#">typo~typo</a></h1>
                    <a href="#">Recettes de Fêtes</a>
                    <a href="#">Les Plats d'Hiver</a>
                    <a href="#">Menu Sportif</a>
                    <a href="#">Facile et Rapide</a>
                    <a href="#">Traditionnel</a>
                    <a href="#">à propos</a>
                </nav>
            </header>
        </nav> 
    </section>


    <section class="navigation">
        <ul class="recette">
            <li>Les plats de Noël</li>
            <li>Les plats de nos Grand-Mères</li>
            <li>Mieux manger</li>
            <li>Recettes rapides</li>
            <li>Autres recettes</li>
        </ul>
    </section>
    <h1 class="h1">Story</h1>
    <section id="story">
     
     
        <h3 id="sucre">SUCRÉ</h3>
        <img class="stor" src="gg.webp"  alt="churros sucré">
        
   
        
        <h3>ON SE RÉCHAUFFE</h3>
        <img class="stor" src="soupe.jpg" alt="soupe">
        
        <h3>FRUITS DE MER</h3>
        <img class="stor" src="aa.webp" alt="fruits de mer">
        
        <h3>GRATINÉS</h3>
        <img class="stor" src="e.jpeg" alt="gratin">

        <h3>salé</h3>
        <img class="stor" src="z.webp" alt="gratin">
    
    </section>
<!--
    <section>
        <img src="b.jpeg" alt="">
    </section> -->

</header>
</body>
    <script>
        document.querySelector( '.burger') .addEventListener( 'click', function (e) {
            e.preventDefault;
            this.className = this.className === 'burger' ? 'burger on' : 'burger';
        });
    </script>
</html>
```

**Comment by Muriel13** [comment]
```css
`* {
margin: 0;
padding: 0;
outline: none;
}
body {
display: flex;
background: #FFEFEF;
width: 100%;
height: auto;
}
#navigation {
background-color: #fff7f7;
}
.header {
background-image: url('https://pixabay.com/fr/photos/cuisine-italienne-alimentaire-2378729/');
}
/* #recherche {
background: white;
} */
.logo {
width: 7%;
margin-left: 80%;
margin-top: 2%;
border-radius: 50%;
}

/bare de recherche/
.form {
position: relative;
height: 10%;
margin-left: 30%;
margin-top: -70px;

}

#search {
width: 50%;
height: 39%;
font-size: 20px;
}
#GO {
width: 6%;
margin-left: -7%;
background-color: rgb(0, 0, 0);
color: aliceblue;
}
/partie2/
.navigation {
display: inline-flex;
background: #2B9348;
width: 100%;
height:13%;
}
.recette {
display: inline-flex;
list-style-type: none;
font-weight: bold;
margin-left: 30%;
padding-top: 2%;

}
ul > li {
padding-left: 3%;
font-size: 14px;
}

/* Menu Burger */

#wrap {
display: flex;
font-family: sans-serif;
color: white;
font-size: 12px;
line-height: 1.6;
margin-top: -6%;

transition: transform .4s cubic-bezier(.25, .1, .25, 1);
}

#wrap:not(:target) {
transform: translate3d(-335px, 0, 0);
}

#wrap:target {
transform: translate3d(0, 0, 0);
}

#open,
#close {
height: 44px;
text-align: right;
display: block;
margin-right: -30px;
}

#wrap:target #open,
#wrap:not(:target) #close {
display: none;
}

#wrap:target #open {
display: none;
}

.nav a {
color: white;
text-decoration: none;
display: block;
}

.header {
background: rgb(0, 0, 0);
width: 360px;
padding: 0 20px;
display:inline-block;
vertical-align:top;
}

.nav {
padding: 25px;
}

.main {
padding: 25px;
flex: 1;
display:inline-block;
}

p {
max-width: 590px;
color:#306;
}
#story {
display: inline-flex;
background: white;
padding-top: 2%;
padding-left: 9%;
}

.stor {
width: 9%;
height:80%;
border-radius: 50%;
}
h3{
margin-top: 8%;
margin-left: 5%;
font-size: 10px;
}
.h1{
background: white;
padding-left: 50%;
padding-top: 30px;
}
```

**Comment by Nabilabilalla** [comment]
```css
* {
  margin: 0;
  padding: 0;
  outline: none;
}
body {
  display: flex;
  background: #ffffff;
  width: 100%;
  height: auto;
}
#navigation {
  background-color: #fff7f7;   
}
 .header {
 background-image: url('https://pixabay.com/fr/photos/cuisine-italienne-alimentaire-2378729/');
} 
/* #recherche {
  background: white;
} */
.logo {
  width: 7%;
  margin-left: 80%;
  margin-top: 2%;
  border-radius: 50%;
}

/*bare de recherche*/
.form {
  position: relative;
  height: 10%;
  margin-left: 30%;
  margin-top: -70px;

}

#search {
  width: 50%;
  height: 39%;
  font-size: 20px;
}
#GO {
width: 6%;
margin-left: -7%;
background-color: #2B9348;
color: aliceblue;
} 
/*partie2*/
.navigation {
  display: inline-flex;
  background: #2B9348;
  width: 100%;
  height:5%;
}
.recette {
  display: inline-flex;
  list-style-type: none;
  font-weight: bold;
  margin-left: 30%;
  padding-top: 2%; 
 
}
ul > li {
  padding-left: 3%;
  font-size: 14px;
}

/* Menu Burger */

#wrap {
  display: flex;
  font-family: sans-serif;
  color: white;
  font-size: 12px;
  line-height: 1.6;
  margin-top: -6%;
  
  transition: transform .4s cubic-bezier(.25, .1, .25, 1);
}

#wrap:not(:target) {
  transform: translate3d(-335px, 0, 0);
}

#wrap:target {
  transform: translate3d(0, 0, 0);
}

#open,
#close {
  height: 44px;
  text-align: right;
  display: block;
  margin-right: -30px;
}

#wrap:target #open,
#wrap:not(:target) #close {
  display: none;
}

#wrap:target #open {
  display: none;
}

.nav a {
  color: white;
  text-decoration: none;
  display: block;
}

.header {
  background: #2B9348;
  width: 360px;
  padding: 0 20px;
  display:inline-block;
  vertical-align:top;
}

.nav {
  padding: 25px;
}

.main {
  padding: 25px;
  flex: 1;
  display:inline-block;
}

p {
  max-width: 590px;
  color:#306;
}
#story {
  display: inline-flex;
  background: white;
  padding-top: 2%;
  padding-left: 9%;
 
}

.stor {
  width: 9%;
  height:80%;
  border-radius: 50%;
  border: solid #2B9348;
}
h3{
  margin-top: 8%;
  margin-left: 5%;
  font-size: 10px;
  text-align: right;
}
.h1{
  background: white;
  padding-left: 50%;
  padding-top: 30px;
}
.AA{
  width: 20%;
  margin-left: 30%;
  margin-top: 5%;
  opacity: 0.4;
}
.livre{
  width: 80%;

  padding-left: 10%;
}
.vitamine{
  margin-left: 20%;
  margin-top: -44%;
  line-height: 1.8em;
}
.vitamine2{
  margin-left: 53%;
  margin-top: -35%;
  line-height: 1.8em;
}
.vite{
  margin-left: 32%;
  width: 18%;
  margin-top: -30%;
  opacity: 0.6;
  border-radius: 20%;
}
.p{
  color: #2B9348;
}
```

**Comment by Nabilabilalla** [comment]
```html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="cuisine.css">
    <title> Recette </title>
</head>

<body>

    <header>
        <section id="form">
        <img class="logo" src="logu.jpeg" alt="Logo Cuisine">

        <div class="form">
       <form>
  <input id="search" type="search" placeholder="Search..." autofocus required />
  <button id="GO" type="submit">Go</button>    
</form>
        </div>
        </section>

    <section class="content">
         <nav class="menu">
        <div id="wrap">
            <header class="header">
                <nav class="nav">
                    <a href="#wrap" id="open">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="34px" height="27px" viewBox="0 0 34 27" enable-background="new 0 0 34 27" xml:space="preserve">
                        <rect fill="#FFFFFF" width="34" height="4"/>
                        <rect y="11" fill="#FFFFFF" width="34" height="4"/>
                        <rect y="23" fill="#FFFFFF" width="34" height="4"/>
                        </svg>
                    </a>
                    <a href="#" id="close">×</a>
                    <h1><a href="#">typo~typo</a></h1>
                    <a href="#">Recettes de Fêtes</a>
                    <a href="#">Les Plats d'Hiver</a>
                    <a href="#">Menu Sportif</a>
                    <a href="#">Facile et Rapide</a>
                    <a href="#">Traditionnel</a>
                    <a href="#">à propos</a>
                </nav>
            </header>
            <img class="AA" src="A.webp" alt="">
           
        </nav> 
        
    </section>


    <section class="navigation">
        <ul class="recette">
            <li>Les plats de Noël</li>
            <li>Les plats de nos Grand-Mères</li>
            <li>Mieux manger</li>
            <li>Recettes rapides</li>
            <li>Autres recettes</li>
        </ul>
    </section>
    <h1 class="h1">Story</h1>
    <section id="story">
     
     
        <h3 id="sucre">SUCRÉ</h3>
        <img class="stor" src="gg.webp"  alt="churros sucré">
        
   
        <h3>ON SE RÉCHAUFFE</h3>
        
        <img class="stor" src="soupe.jpg" alt="soupe">
        
        <h3>FRUITS DE MER</h3>
        <img class="stor" src="aa.webp" alt="fruits de mer">
        
        <h3>GRATINÉS</h3>
        <img class="stor" src="e.jpeg" alt="gratin">

        <h3>SALé</h3>
        <img class="stor" src="z.webp" alt="gratin">
    
    </section>

    <section>
        <img class="livre" src="b.jpeg" alt="">
        <div class="vitamine">
            <h1>À quoi servent les vitamines ?</h1>
            <br>
        <p class="p">Les vitamines ont chacune une fonction importante pour le <br> fonctionnement de l'organisme, et sont au nombre de 13 :</p>
        <li>vitamine A ;</li>
        <li>vitamine B2 ;</li>
        <li>vitamine B3 ;</li>
        <li>vitamine B5 ;</li>
        <li>vitamine B6 ;</li>
        <li>vitamine B8 ;</li>
        <li>vitamine B12 ;</li>
        <li>vitamine B9 ;</li>
        <li>vitamine C ;</li>
        <li>vitamine D ;</li>
        <li>vitamine E ;</li>
        <li>vitamine K.</li>
    </div>
    <div class="vitamine2">
        <h1>Quels sont les bons apports <br> en vitamines ?</h1><br>
        <p class="p">La plupart des vitamines sont apportées par l'alimentation. <br> Cependant, les apports en vitamine D proviennent en grande <br> partie des rayons UV, et la vitamine K est également fabriquée <br> par les bactéries de l'intestin. Les apports sont calculés en <br> microgrammes ou en milligrammes. Les apports pour les <br> principales vitamines sont : </p> 
        <li>vitamine A : 800 mcg ;</li>
        <li>vitamine B9 : 400 mcg ;</li>
        <li>vitamine B12 : 2,4 mcg ;</li>
        <li>vitamine C : 80 mg ;</li>
        <li>vitamine D : 200 µl ;</li>
        <li>vitamine E : 15 mg ;</li>
        <li>vitamine K : 100 mcg.</li>
    </div>
    <img class="vite" src="vitamine.jpeg" alt="">
    </section> 

</header>
</body>
    <script>
        document.querySelector( '.burger') .addEventListener( 'click', function (e) {
            e.preventDefault;
            this.className = this.className === 'burger' ? 'burger on' : 'burger';
        });
    </script>
</html>
```

**Comment by Muriel13** [comment]
<section id="trouve">
            <div class="trouver">
                <h1 class="trouver1">TROUVER</h1>
                <ul>
                    <li>Supermarchés</li>
                    <li>Particulier</li>
                    <li>Bio</li>
                    <li>Boucheries</li>
                    <li>Traiteurs</li>
                    <li>Boulangeries</li>
                    <li>Produits de bases</li>
                </ul>
            </div>
        </section>

**Comment by Muriel13** [comment]
```html
<section id="trouve">
            <div class="trouver">
                <h1 class="trouver1">TROUVER</h1>
                <ul>
                    <li>Supermarchés</li>
                    <li>Particulier</li>
                    <li>Bio</li>
                    <li>Boucheries</li>
                    <li>Traiteurs</li>
                    <li>Boulangeries</li>
                    <li>Produits de bases</li>
                </ul>
            </div>
        </section>
        
        <section>
            <div>
                <h1 id="map">MAP</h1>
            </div>
        </section>

        <div>
            <section>
                <h1>CONTACT</h1>
            </section>

            <section>
                <img src="" alt="">
            </section>
        </div>
```

**Comment by Muriel13** [comment]
> <section>
            <div>
                <h1>MAP</h1>
            </div>
        </section>

**Comment by Muriel13** [comment]
```css  
/* Partie commerce */
#trouve {
  display: inline-flex;
  background: #2B9348;
  width: 100%;
  height:5%;
  margin-left: 30px;
  margin-top: 1500px;
}
.trouver1 {
  text-align: center;
}
.trouver {
  display: inline-flex;
  list-style-type: none;
  font-weight: bold;
  margin-left: 30%;
  padding-top: 2%; 
 
}
ul > li {
  padding-left: 3%;
  font-size: 14px;
}
```

**Comment by Muriel13** [comment]
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf_8" />
        <link rel="stylesheet" href="manger.css" />
        <title>Mieux Manger</title>
    </head>
    <body>
        
    </body>
</html>
```

**Comment by Muriel13** [comment]
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf_8" />
        <link rel="stylesheet" href="platsnoel.css">
        <title>Les Plats de Noël</title>
    </head>
    <body>
        
    </body>
</html>
```

**Comment by Muriel13** [comment]
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf_8" />
        <link rel="stylesheet" href="plats.css">
        <title>Plats de nos Grand-Mères</title>
    </head>
    <body>
        
    </body>
</html>
```

**Comment by Muriel13** [comment]
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf_8" />
        <link rel="stylesheet" href="rapide.css">
        <title>Recettes Rapides</title>
    </head>
    <body>
        
    </body>
</html>
```

**Comment by Muriel13** [comment]
pour la partie MAP
```css
/* partie MAP */
.map {
  
}
```
```html
<section>
            <div>
                <h1 id="map">MAP</h1>
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d11616.543546186733!2d5.3662966!3d43.290475900000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sfr!4v1609327078656!5m2!1sfr!2sfr" width="400" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
        </section>
```

**Comment by Muriel13** [comment]
```html
<!-- <section>
            <div>
                <h1 id="map">MAP</h1>
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d11616.543546186733!2d5.3662966!3d43.290475900000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sfr!4v1609327078656!5m2!1sfr!2sfr" width="400" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
        </section> -->

       <!-- <div>
            <section>
                <h1>CONTACT</h1>
            </section> 

            <section>
                <img src="" alt="">
            </section>
        </div> -->
```

**Comment by Muriel13** [comment]
```css
/* partie MAP */
/* .map {
  top: 800px;
} */
```

**Comment by Muriel13** [comment]
```css
/* Partie commerce */
/* #trouve {
  display: inline-flex;
  background: #2B9348;
  width: 100%;
  height:5%;
  margin-left: 30px;
  margin-top: 1500px;
}
.trouver1 {
  text-align: center;
}
.trouver {
  display: inline-flex;
  list-style-type: none;
  font-weight: bold;
  margin-left: 30%;
  padding-top: 2%; 
 
}
ul > li {
  padding-left: 3%;
  font-size: 14px;
} */
```

**Comment by Muriel13** [comment]
```html
<!-- <section id="trouve">
            <div class="trouver">
                <h1 class="trouver1">TROUVER</h1>
                <ul>
                    <li>Supermarchés</li>
                    <li>Particulier</li>
                    <li>Bio</li>
                    <li>Boucheries</li>
                    <li>Traiteurs</li>
                    <li>Boulangeries</li>
                    <li>Produits de bases</li>
                </ul>
            </div>
        </section> -->
```

**Comment by Nabilabilalla** [comment]
```css
 #trouve {
 
  background: #2B9348;
  width: 100%;
  height:5%;
 
  margin-top: 8%;
}
.trouver1 {

  margin-left: 30%;
}
.trouver {
  list-style-type: none;
  font-weight: bold;
  margin-left: 20%;
  padding-top: 3%; 
 
}
ul > li {
  padding-left: 3%;
  font-size: 14px;
  display: inline-flex;
} 
```

**Comment by Nabilabilalla** [comment]
```css
    <section id="trouve">
            <div class="trouver">
                <h1 class="trouver1">TROUVER</h1>
                <ul>
                    <li>Supermarchés</li>
                    <li>Particulier</li>
                    <li>Bio</li>
                    <li>Boucheries</li>
                    <li>Traiteurs</li>
                    <li>Boulangeries</li>
                    <li>Produits de bases</li>
                </ul>
            </div>
        </section> 
        <section>
            <iframe src="https://www.google.com/maps/d/embed?mid=1pWfMrbhAWG8TnWBafT76bSaeIQ1v2hKr" width="1340" height="480"></iframe>
        </section>
```

**Comment by Nabilabilalla** [comment]
```css
/* Partie commerce */
 #trouve {
 
  background: #2B9348;
  width: 100%;
  height:5%;
 
  margin-top: 12%;
}
.trouver1 {

  margin-left: 30%;
}
.trouver {
  list-style-type: none;
  font-weight: bold;
  margin-left: 20%;
  padding-top: 3%; 
 
}
ul > li {
  padding-left: 3%;
  font-size: 14px;
  display: inline-flex;
} 
/*contact*/


#contact {
width: 500px;
margin-left: 7%;
margin-top: 2%;
background:white;
position: relative;
}


#contact h1 {
background:  #2B9348;
font-family: Oswald ,sans-serif;
font-size: 1.75em;
padding: 0.6em 0 0.6em 0.4em;
color: white;
text-shadow: 0 0.06em 0 #2B9348;
position: relative;
}


.input_wrapper {
position: relative;
}

.input_wrapper input[type="text"] {
margin-top: 1em;
display: block;
width: 100%;
background: white;
border: 1px solid #DADADA;
box-shadow: 0 0 1px 0 #E4E4E4;
-webkit-box-sizing: border-box;
-moz-box-sizing: border-box;
box-sizing: border-box;
padding: 1em;
-webkit-transition: all 250ms ease;
-moz-transition: all 250ms ease;
-ms-transition: all 250ms ease;
-o-transition: all 250ms ease;
transition: all 250ms ease;
color: #5E5E5E;
text-indent: 15%;
}

.input_wrapper label {
position: absolute;
left: 0;
top: 0;
height: 100%;
background:  #2B9348;
color: white;
font-family: Oswald ,sans-serif;
box-sizing: border-box;
width: 15%;
text-align: center;
line-height: 2.8em;

}

.textarea_wrapper textarea {
margin-top: 20px;
display: block;
width: 100%;
  min-height:150px;
background: white;
border: 1px solid #DADADA;
box-shadow: 0 0 1px 0 #E4E4E4;
-webkit-box-sizing: border-box;
-moz-box-sizing: border-box;
box-sizing: border-box;
padding: 1em;
color: #5E5E5E;
}

.submit_wrapper {
text-align: center;
}
.submit_wrapper input {
text-align: center;
display: inline-block;
width: 40%;
height: 50px;
margin-top: 1em;
margin-bottom: 6px;
cursor: pointer;
background:  #2B9348;
color: white;
font-family: Oswald ,sans-serif;
font-size: 1em;
border: none;
-webkit-box-shadow: 1px 1px 0 0  #2B9348,2px 2px 0 0  #2B9348,3px 3px 0 0  #2B9348;
box-shadow: 1px 1px 0 0  #2B9348,2px 2px 0 0  #2B9348,3px 3px 0 0  #2B9348;
}


/**********animation contact************/


.container{
  margin-left: 70%;
  margin-top: 1%;
  width: 70px;
  height: 70px;
  transform-origin:center bottom;
  animation-name: flicker;
  animation-duration:3ms;
  animation-delay:200ms;
  animation-timing-function: ease-in;
  animation-iteration-count: infinite;
  animation-direction: alternate;
}

.flame{
  bottom:0;
  position:absolute;
  border-bottom-right-radius: 50%;
  border-bottom-left-radius: 50%;
  border-top-left-radius: 50%;
  transform:rotate(-45deg) scale(1.5,1.5);
}

.yellow{
  left:15px; 
  width: 30px;
  height: 30px;
  background:gold;
  box-shadow: 0px 0px 9px 4px gold;
}

.orange{
  left:10px; 
  width: 40px;
  height: 40px;
  background:orange;
  box-shadow: 0px 0px 9px 4px orange;
}

.red{
  left:5px;
  width: 50px;
  height: 50px;
  background:OrangeRed;
  box-shadow: 0px 0px 5px 4px OrangeRed;
}

.white{
  left:15px; 
  bottom:-4px;
  width: 30px;
  height: 30px;
  background:white;
  box-shadow: 0px 0px 9px 4px white;
}

.circle{
  border-radius: 50%;
  position:absolute;  
}

.blue{
  width: 10px;
  height: 10px;
  left:25px;
  bottom:-25px; 
  background: SlateBlue;
  box-shadow: 0px 0px 15px 10px SlateBlue;
}



@keyframes flicker{
  0%   {transform: rotate(-1deg);}
  20%  {transform: rotate(1deg);}
  40%  {transform: rotate(-1deg);}
  60%  {transform: rotate(1deg) scaleY(1.04);}
  80%  {transform: rotate(-2deg) scaleY(0.92);}
  100% {transform: rotate(1deg);}
}
/*****casrolle*****/
.casrol{

  width: 15%;
  margin-top: -2%;
  margin-left: 68%;
  transform-origin:center bottom;
  animation-name: flicker;
  animation-duration:3ms;
  animation-delay:200ms;
  animation-timing-function: ease-in;
  animation-iteration-count: infinite;
  animation-direction: alternate;
}
img .casrol{
  margin-top: -9%;
}
@keyframes flicker{
  0%   {transform: rotate(-1deg);}
  20%  {transform: rotate(1deg);}
  40%  {transform: rotate(-1deg);}
  60%  {transform: rotate(1deg) scaleY(1.04);}
  80%  {transform: rotate(-2deg) scaleY(0.92);}
  100% {transform: rotate(1deg);}
}

/**lég**/

.tom{
  width: 5%;
  margin-top: -10%;
  margin-left: 70%;
  position: relative;
  animation-name: example;
  animation-duration: 6s;
  animation-timing-function: linear;
  animation-delay: 1s;
  animation-iteration-count: infinite;
  animation-direction: alternate;

}
@keyframes example {
  0%   { left:0px; top:0px;}
  25%  {left:20px; top:0px;}
  50%  {left:0px; top:80px;}
  75%  {display: none;}
  100% {display: none;}
}
.toma{
  width: 4%;
  margin-top: -19%;
  margin-left: 65%;
  position: relative;
  animation-name: ex;
  animation-duration: 6s;
  animation-timing-function: linear;
  animation-delay: 2s;
  animation-iteration-count: infinite;
  animation-direction: alternate;

}
@keyframes ex {
  0%   { left:0px; top:0px;}
  25%  {left:90px; top:0px;}
  50%  {left:0px; top:0px;}
  75%  {display: none;}
  100% {display: none;}
}
.tomn{
  width: 7%;
  margin-top: -12%;
  margin-left: 59%;
  position: relative;
  animation-name: exa;
  animation-duration: 6s;
  animation-timing-function: linear;
  animation-delay: 3s;
  animation-iteration-count: infinite;
  animation-direction: alternate;
}
@keyframes exa {
  0%   { left:20px; top:0px;}
  25%  {left:70px; top:0px;}
  50%  {left:0px; top:0px;}
  75%  {left:0px; top:0px;}
  100% {left:0px; top:0px;}
}
.tamm{
  width: 7%;
  margin-top: -12%;
  margin-left: 53%;
  position: relative;
  animation-name: exam;
  animation-duration: 6s;
  animation-timing-function: linear;
  animation-delay: 4s;
  animation-iteration-count: infinite;
  animation-direction: alternate;
}
@keyframes exam {
  0%   { left:20px; top:0px;}
  25%  {left:70px; top:0px;}
  50%  {left:0px; top:0px;}
  75%  {left:0px; top:0px;}
  100% {left:90px; top:0px;}
}
    
  
    .animation{
      margin-top: -25%;
    }
    /**footer**/
    footer {
      margin-top: 8%;
    }
    
    .footer-distributed {
      background-color: #292c2f;
      box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);
      box-sizing: border-box;
      font: bold 16px sans-serif;
    }
    
    .footer-distributed h3 {
      color: #ffffff;
      font: normal 36px 'Cookie', cursive;
    }
    ```
